name: Action Workflow

on: [push]

jobs:
    run-github-actions:
        runs-on: windows-latest
        steps:
        - name: Simple Javascript Action
          id: hello
          uses: actions/hello-world-javascript-action@v1
          with:
            who-to-greet: Neeraj

        - name: Get the Output Time
          run: echo "${{ steps.hello.outputs.time}}"


