name: Node.js App Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Run Node.js Application
      run: node app.js &
    
    - name: Wait for Server to Start
      run: sleep 5  # Adjust sleep time as needed for your application to start
    
    - name: Test Application
      run: curl http://localhost:3000
